services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: unit-state-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d unit-state-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/doccerz/unit-state-microservice:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/unit-state-db
      DATABASE_SCHEMA: unit-state-service
    depends_on:
      postgres:
        condition: service_healthy
